name: CD

on:
  push:
    branches: [blog]
    tags-ignore: ["**"]

jobs:
  release:
    if: ${{ ! startsWith(github.event.head_commit.message, 'chore(release)') }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4  # Align with production Ruby version
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cache Node.js dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Cache Ruby gems
      - name: Cache Ruby gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-

      # Install dependencies and build
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}

  publish:
    needs: release
    uses: ./.github/workflows/publish.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      BUILDER: ${{ secrets.BUILDER }}
