name: CI

on:
  push:
    branches:
      - main
      - "hotfix/*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/ci.yml"
      - .gitignore
      - "docs/**"
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["3.4"]  # Reduced to just Ruby 3.4 if that's your production version

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For posts' lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true  # Caching Ruby gems

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Cache Node.js dependencies to speed up future builds
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Assets
        run: npm ci && npm run build  # 'npm ci' ensures a clean install

      # Optional: Remove if not needed
      - name: Test Site
        run: bash tools/test.sh  # Only if needed for testing